INSERT INTO shoes (gender, price, brand, size, seller_id, image_url, is_sold, description)
VALUES ('male', '100', 'Adidas', '10', '1', 'docs\pics\adidas 1.jpg', 'false', 'Brand new, out of the box, white Adidas shoes.'),
('male', '120', 'Adidas', '9', '2','docs\pics\adidas 2.jpg', 'false', 'Never used before, perfect condition!'),
('male', '500', 'Air jordan', '12', '3', 'docs\pics\air jordan 3.jpg', 'false', 'Mint condition. Special edition'),
('female', '99', 'Nike', '8', '4', 'docs\pics\nike 4.png', 'false', 'White air nike shoes, great condition'),
('male', '205', 'Puma', '11', '5','docs\pics\puma 5.png', 'false', 'New, really comfortable'),
('female', '100', 'Puma', '7', '1','docs\pics\puma 6.png', 'false', 'Nice faded women sports shoes. Great design'),
('female', '108', 'Puma', '8', '2','docs\pics\puma 7.png', 'false', 'Blue running shoes. Limited edition'),
('male', '400', 'Yeezy', '10', '3','docs\pics\yeezy 8.png', 'false', 'Unique design! Rare collection.'),
('male', '189', 'Yeezy', '4', '4', 'docs\pics\yeezy 9.png', 'false', 'Shoes from space, designed by aliens'),
('male', '95', 'DC', '9', '5', 'docs\pics\dc 10.png', 'false', 'New pair, never used them'),
('male', '99', 'DC', '11', '1', 'docs\pics\dc 11.png', 'false', 'New collection, looks great!'),
('female', '105', 'DC', '7', '2', 'docs\pics\dc 12.png', 'false', 'Beautiful model and colors'),
('female', '108', 'DC', '6', '3', 'docs\pics\dc 13.png', 'false', 'Casual shoes with a nice look'),
('male', '112', 'Under Armour', '11', '4', 'docs\pics\UA 14.png', 'false', 'Sports shoes with a great look'),
('female', '104', 'Under Armour', '7', '5', 'docs\pics\UA 15.PNG', 'false', 'Perfect for running. Great quality for the price'),
('female', '108', 'Under Armour', '11', '1', 'docs\pics\UA 16.PNG', 'false', 'Mint condition and looks great'),
('female', '108', 'Under Armour', '9', '2', 'docs\pics\ua 17.PNG', 'false', 'Women sports shoes, really comfortable'),
('male', '112', 'Vans', '13', '3', 'docs\pics\vans 18.png', 'false', 'Casual shoes for everyday, classic look'),
('male', '108', 'Vans', '12', '4', 'docs\pics\vans 19.png', 'false', 'Brand new, out of the box'),
('female', '132', 'Vans', '7', '5', 'docs\pics\vans 20.png', 'false', 'Shoes for every day activities'),
('female', '124', 'Vans', '6', '1', 'docs\pics\vans 21.png', 'false', 'Go anywhere in style with this amazing pair!'),
('male', '158', 'Salomon', '12', '2', 'docs\pics\salomon 22.png', 'false', 'Hiking shoes, perfect for the coming season.'),
('female', '153', 'Salomon', '11', '3', 'docs\pics\salomon 23.png', 'false', 'Hiking shoes for women. Enjoy your exercise to the max.'),
('male', '168', 'Salomon', '9', '4', 'docs\pics\salomon 24.png', 'false', 'Great looking hiking shoes'),
('female', '163', 'Salomon', '7', '5', 'docs\pics\salomon 25.png', 'false', 'Keep up the pace with these awesome hiking shoes!'),
('female', '113', 'Hoka', '6', '1', 'docs\pics\hoka 26.png', 'false', 'Great for women that enjoy sports'),
('female', '111', 'Hoka', '10', '2', 'docs\pics\hoka 27.png', 'false', 'Enjoy your workout with these brand new Hokas!'),
('male', '100', 'Converse', '12', '3', 'docs\pics\converse 28.png', 'false', 'Classic look. Walk in style.'),
('male', '117', 'Converse', '11', '4', 'docs\pics\converse 29.png', 'false', 'New look. Really comfortable.'),
('female', '111', 'Converse', '10', '5', 'docs\pics\converse 30.png', 'false', 'Classic look with a nice color'),
('female', '115', 'Converse', '9', '1', 'docs\pics\converse 31.png', 'false', 'Classic model with a girly touch'),
('male', '650', 'Edgerunners', '10', '2', 'docs\pics\alvin 32.png', 'false', 'Alvin special shoes');
-- not sure how to link images
